# Generated by Django 4.1.1 on 2023-04-03 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(
                default=uuid.UUID("5ebb2a76-4d58-4f82-a517-2208f19e74ef"), unique=True
            ),
        ),
    ]
