# Generated by Django 4.1.1 on 2023-04-03 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(
                default=uuid.UUID("206ae7b6-0354-4c69-a2a1-52925f962c23"), unique=True
            ),
        ),
    ]
