# Generated by Django 4.1.1 on 2023-04-03 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(
                default=uuid.UUID("23a9cd1e-c822-41a5-914d-63619e70ddf2"), unique=True
            ),
        ),
    ]
